# Generated by Django 4.0.1 on 2022-01-10 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_username_alter_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profle_image',
            new_name='profile_image',
        ),
    ]
