# Generated by Django 4.0.1 on 2022-01-10 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_location_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='desription',
            new_name='description',
        ),
    ]
