# Generated by Django 4.0.1 on 2022-01-11 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_social_likendin_profile_social_linkedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='short_into',
            new_name='short_intro',
        ),
    ]
