# Generated by Django 4.0.1 on 2022-01-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['is_read', '-create_at']},
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(default='01/02/2022'),
            preserve_default=False,
        ),
    ]
